### ISSUE TITLE
Getting systemd-docker

### ISSUE THREAD

**Issue by amouat** [ibuildthecloud/systemd-docker#26]
Hi, I'm trying to use systemd-docker and running into:

```
$ go get github.com/ibuildthecloud/systemd-docker
package github.com/ibuildthecloud/systemd-docker
	imports github.com/docker/docker/opts
	imports github.com/Sirupsen/logrus
	imports github.com/docker/libtrust
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/src/go/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
```

I did see you'd opened a docker issue about this https://github.com/docker/docker/issues/11699.

Unfortunately, I'm not a go programmer, so I don't understand the fix. Is there any chance you could provide a binary? For obvious reasons, most of us are going to be using 64bit linux...

**Comment by ibuildthecloud** [comment]
You can just do a git clone and run ./build.  Go get is broken because of the reason you pointed to.  If you run the build script it use the vendored libraries.

**Comment by amouat** [comment]
Thanks, just me being dumb then!

Might be worth adding that to the instructions for other idiots like me though.
