### ISSUE TITLE
docker/pkg/mflag dependency no longer exists

### ISSUE THREAD

**Issue by tomp61** [ibuildthecloud/systemd-docker#42]
When I try to build systemd-docker, it fails with the error message 'cannot find package "github.com/docker/docker/pkg/mflag"', and indeed, it looks like that package was removed from the docker sources in June 2016.

At this point I'm trying to decide whether it makes more sense to try to fix this, or to find another way to deploy Docker containers...

Tom

**Comment by davidfrechette** [comment]
The missing package is included in the repo if you download it.
So to make it worked, I've exported my GOPATH variable to : 
`export GOPATH=$PWD/Godeps/_workspace/`

Where $PWD is the root of systemd-docker source files

And then `go build`

For the record, I'm a newbie with GO so pardon me if this is making your eyes bleeding.

**Comment by tomp61** [comment]
Thanks!  With that, the build goes fine.  Moreover, I see now that this is done automatically in the `build` script, which I didn't think to use.  Thanks for pointing me in the right direction.
